# Generated by Django 5.2.3 on 2025-09-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.CharField(default='me@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
